### ISSUE TITLE
API 0.6: Support layer caching being opt-in

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#103]
In order to support [Buildpack API 0.6](https://github.com/buildpacks/spec/releases/tag/buildpack%2Fv0.6), we need to support layer caching now being opt-in:

> Buildpacks must explicitly opt-in to layer re-use by appending to `<layers>/<layer>.toml` (https://github.com/buildpacks/spec/issues/132, https://github.com/buildpacks/spec/pull/209, [RFC 0052](https://github.com/buildpacks/rfcs/blob/main/text/0052-opt-in-layer-caching.md)).

Spec:
https://github.com/buildpacks/spec/blob/buildpack/0.6/buildpack.md#layer-types

We'll need to:
1. Make sure that the layer types are optional when the layer manifest is being serialised ([they are](https://github.com/Malax/libcnb.rs/blob/f46bdda85838c9cc21cd1de3243d4160b85afc12/src/data/layer_content_metadata.rs#L11-L21), but we should add tests)
2. Decide on the UX for setting the layer types again on the "keep layer" flow, given currently, the layers are only set typically on create: https://github.com/Malax/libcnb.rs/blob/f46bdda85838c9cc21cd1de3243d4160b85afc12/examples/example-02-ruby-sample/src/layers/bundler.rs#L83

GUS-W-10025493.

**Comment by schneems** [comment]
## Problem

Due to #103 the LayerLifecycle `ValidateResult::KeepLayer` will no longer work as intended. When that is returned from `validate` it keeps the existing toml file, but that file no longer has the information about types (build, cache, launch) anymore. That effectively meanins that using "keep layer" will be the same as deleting the layer.

## Additional problems

- Update/Create inconsistent types

While investigating this we noticed that the interface of LayerLifecycle allows for different behaviors during `ValidateResult::RecreateLayer`` and `ValidateResult::UpdateLayer` which Ed and I think is a bug. If the layer is being created or updated it should always have the same types.

For competiting art, the Ruby (rewrite) buildpack's layer types are defined globally https://github.com/heroku/buildpacks-ruby/blob/cac3caf0d31b4a69c6ce1743ad63b7e948a4764c/lib/heroku_buildpack_ruby.rb#L39-L41

## Solutions

### Do nothing

Consequences:


If we do nothing programmers using "keep" will mysteriously have their layers deleted on the second deploy which would be confusing and difficult to understand

### Remove the KeepLayer

We could remove `ValidateResult::KeepLayer` all together to force the developer to either update or create the types every time. 

Consequences: 

This would force developers to try to immitate a "keep" state with one of their other existing states. If I was going to do this, I might put an additional conditional in my `update` action to only write the types to disk and put my "keep" logic in there.

### Update KeepLayer enum to add types

We could make the `ValidateResult::KeepLayer` to hold `ValidateResult::KeepLayer(LayerContentTypeTable)` and then update LayerLifecycle to update the TOML on "keep" state. 

**Consequences:**

It would force developers using `KeepLayer` to update their code and solve the ambiguity. It would make the "Update/Create inconsistent types" problem worse as there's no enforcement or guarantee that the three states would return the same types.


### Move type declaration out of `update` and `create`

Currently both `update` and `create` can write types (build, launch, cache). As mentioned before these can be inconsistent. If we change the interface so that these functions instead return metadata rather than a full `LayerContentMetadata`  (which includes types and metadata), and then added another interface to declare the types, then this would give libcnb enough information to "do the right thing" by default. When it sees `KeepLayer` it can re-write the types it knows that it has.

You can see some examples of code using Layer lifecycle here https://github.com/heroku/buildpacks-jvm/tree/main/buildpacks/jvm-function-invoker/src/layers

**Consequences:**

This would force all developers using this interface to update their code (instead of just the ones using KeepLayer). It would also guarantee consistency between the three states (create, update, keep) which addresses both stated problems.

It might be possible to simplify the generic type signature of LayerLifecycle since it would no longer need to know about `LayerContentMetadata` or `GenericMetadata` for the default case.

**Interface ideas**

Here are some possible interface changes:


- Idea: Impl can require `cache`, `launch`, `build` keys:

```rs
pub struct OptLayerLifecycle {}
```

would become

```rs
pub struct OptLayerLifecycle {
    cache: bool,
    build: bool,
    launch: bool,

}
```

And invocation in `build.rs` would change from:

```rs
    let run_sh_path: PathBuf = execute_layer_lifecycle("opt", OptLayerLifecycle {}, &context)?;
```

to

```rs
    let run_sh_path: PathBuf = execute_layer_lifecycle("opt", OptLayerLifecycle {
      cache: false,
      build: false,
      launch: false
    }, &context)?;
```

Implementaation consequences: The information about what types the created layer uses is more visible in the top level `build.rs` code. Likewise, it's makes working on the low level `opt.rs` file less clear which layers types are visible. 

- Idea: Introduce a new required function that returns `LayerContentTypeTable`

```rs
fn visibility() -> LayerContentTypeTable
```

Implementation consequences: Information about layer types stays in the file as in the current interface.

### Shadow the "types" in the metadata

Since libcnb acts as a middleman between `create`, `update` and writing data to disk, we could add in some extra keys into metadata. That would allow us to record the types to disk, and then later pull them out and store them to use in the event of `KeepLayer`:

```toml
[metadata._libcnb.types]
cache=true
build=false
launch=true
```

**Consequences**

This is kinda gnarly. If this was rails, this is probably what we would do, but it's not very obvious that magic is happening and it would require a lot of gating and manipulation on our part to remove this metadata before it ever got back to the developer's LayerLifecycle code.

### Remove LayerLifecycle in favor of another interface

The layer lifecycle interface does a LOT, it could potentially be decoupled. Essentially all of the pieces right now only work with the full `execute_layer_lifecycle` but instead we could push behavior elsewhere and then choose to re-use it in the Layer Lifecycle or something like it.

I'm having a hard time imagining a different interface though. When I spoke to Ed, it was helpful to think of there being a CRUD actions for the path data and CRUD for the toml file. Part of what makes this layer lifecycle so complicated is there's a 4x4 matrix of operations to support and think about:


|   | C  | R  | U  | D  |
|---|----|----|----|----|
| C | CC | CR | CU | CD |
| R | RC | RR | RU | RD |
| U | UC | UR | UU | UD |
| D | DC | DR | DU | DD |


Currently we don't support deleting, so we're actually runnining into the original problem described in #103. This represents our existing support:


|   | C  | R  | U  | D |
|---|----|----|----|---|
| C | CC | CR | CU |   |
| R | RC | RR | RU |   |
| U | UC | UR | UU |   |
| D |    |    |    |   |

I believe that the innovation of layer lifecycle was in realizing that many operations are coupled. For instance when we detect that a cache is invalidated we don't just need to update the metadata, we also need to update files on disk. Due to that coupling the lifecycle seems to collapse several states:

|   | C  | R  | U  | D |
|---|----|----|----|---|
| C | CC |    |    |   |
| R |    | RR |    |   |
| U |    |    | UU |   |
| D |    |    |    |   |


Which roughly correlates to the 3 "validation" states: update, recreate, and keep (however keep is currently a no-op).

I think it feels heavy because there's a layer of indirection happening (a state machine) and it's not quit clear at first glance how to convert a desired action (say "read the metadata") into those states.

Currently the lifecycle automatically handles these events:

- Creating and re-creating the `layers/<layer>` path
- Creating and re-creating the `layers/<layer>.toml` file
- Reading the `layers/<layer>.toml`
    - Performing a recovery strategy with `layers/<layer>.toml`
- Writing state to to `layers/<layer>.toml` on disk

For another implementation, take a look at the Ruby buildpack.

- Manually build a layer path https://github.com/heroku/buildpacks-ruby/blob/main/lib/heroku_buildpack_ruby.rb#L130
- Pass it to a class https://github.com/heroku/buildpacks-ruby/blob/main/lib/heroku_buildpack_ruby.rb#L158
- Write to the ENV interface (represented in that same layer) https://github.com/heroku/buildpacks-ruby/blob/cac3caf0d31b4a69c6ce1743ad63b7e948a4764c/lib/heroku_buildpack_ruby/bundle_install.rb#L58-L61
- Modify a different layer's ENV value with the same path https://github.com/heroku/buildpacks-ruby/blob/cac3caf0d31b4a69c6ce1743ad63b7e948a4764c/lib/heroku_buildpack_ruby/bundle_install.rb#L72
- That's it.

Bundler just needs the directory, name it will create it if it doesn't exist. I don't need to manually handle cache invalidation `bundle clean` will do this for me automatically. There's no metadata at all for this `gems` layer and its "types" are statically encoded globally here: https://github.com/heroku/buildpacks-ruby/blob/main/lib/heroku_buildpack_ruby.rb#L39

Here's how this flow would be aided from the lifecycle:

- Creating and re-creating the `layers/<layer>` path [used because we write to `layers/<layer>/env.launch` and `layers/<layer>/env.build`]
- Creating and re-creating the `layers/<layer>.toml` file [not used]
- Reading the `layers/<layer>.toml` [not used]
    - Performing a recovery strategy with `layers/<layer>.toml` [not used]
- Writing state to to `layers/<layer>.toml` on disk [not used]

So it would be very heavy to try to fit this workflow into the same state machine. 

An example of metadata use in the same buildpack:

- A metadata specific object is instantiated https://github.com/heroku/buildpacks-ruby/blob/main/lib/heroku_buildpack_ruby.rb#L135
- Passed to a class to install bundler and ruby https://github.com/heroku/buildpacks-ruby/blob/main/lib/heroku_buildpack_ruby.rb#L140
- Then there's a cache "get or get and set" interface (via `fetch`) used: https://github.com/heroku/buildpacks-ruby/blob/cac3caf0d31b4a69c6ce1743ad63b7e948a4764c/lib/heroku_buildpack_ruby/ruby_detect_version.rb#L67


Not to say that any of this is good or desireable, but it's another implementation of an abstraction over the CNB spec and it might help to look at what various contributors desired to do as they're interacting with the lifecycle over CRUD regarding layer metadata and disk contents.

**Comment by edmorley** [comment]
I'm in favour of either:

> Move type declaration out of update and create

or:

> Remove LayerLifecycle in favor of another interface

I'm also not too worried about making people change their code. This library is still young, version pre v1, and I'd rather us make breaking changes if it means we can iterate towards a cleaner API :-)

**Comment by edmorley** [comment]
Meant to say - thank you for the great write-up!
