### ISSUE TITLE
User Defined Metadata Struct

### ISSUE THREAD

**Issue by hone** [Malax/libcnb.rs#14]

**Comment by Malax** [comment]
This would apply to all CNB entities that have a `[metadata]` TOML entry. It would be nice to support parsing the metadata as multiple types instead of forcing the metadata type as CNB entity construction. Basically: 

```
context.buildpack_descriptor.get_metadata::<TypeA>();
context.buildpack_descriptor.get_metadata::<TypeB>();
```

instead of typing it once as part of, for example, `BuildContext`: 

```
BuildContext<GenericPlatform, MetadataTypeA>
```

This allows buildpack authors to support multiple versions of metadata which can easily happen with older cached layers.

**Comment by Malax** [comment]
I also think I want this for [0.2.0](https://github.com/Malax/libcnb/milestone/1), @hone thoughts?

**Comment by hone** [comment]
That sounds good to me. :) I'd like to play with something like this.

**Comment by Malax** [comment]
This has been implemented.
