### ISSUE TITLE
Incorrect data model for StackId

### ISSUE THREAD

**Issue by Malax** [Malax/libcnb.rs#147]
https://github.com/Malax/libcnb.rs/commit/034b2a2f4be62f08ced2ed34a4c3a3ab06b521c4 changed `StackId` so that `*` is a valid `StackId`, which is incorrect.

There can't be a stack named `*`, but you can specify `*` in `buildpack.toml` to indicate that the buildpack is compatible with any stack. Those are very different things.

We should revert `StackId` to its previous implementation and introduce a new type that is used in the buildpack descriptor to model the "compatible with any stack" case. An enum like this comes to mind:

```rust
enum StackCompatibility {
    Any,
    Specific<Vec<StackId>>
}
```

GUS-W-10204027.

**Comment by edmorley** [comment]
@Malax Reading the spec, counter-intuitively, it sounds like the following is allowed:

```toml
[[stacks]]
id = "*"

[[stacks]]
id = "foo"
mixins = ["bar"]
```

This was surprising to me, though reading the [original RFC](https://github.com/buildpacks/rfcs/blob/main/text/0056-any-stack-buildpacks.md), it seems like perhaps in the future the intention was to support arbitrary wildcards (eg `io.buildpacks.stacks.ubuntu.*`), so perhaps that was why (though I could argue that the `"*"` case should be separate from that and the spec insist there is only ever one entry in `stacks` if it is used).

Given this, it seems that the type needs to be a `Vec<StackCompatibility>` not `<Vec<StackId>>`?

Also, since stacks have mixins, I'm presuming `StackCompatibility::Specific` should wrap `Stack` not `StackId`?

**Comment by Malax** [comment]
@edmorley When I was jotting down the idea in the issue description, I did not have the actual definition or spec before me. I should've taken more time before creating this issue, my apologies.

Looking at the RFC, you're right - this is a little more complex but not much. What do you think about changing `Stack` to smth. like this?

```rust
enum Stack {
    Wildcard,
    Concrete { id: StackId, mixins: Vec<String> },
}
```

Now that I see it, `mixins` should not be `Vec<String>` but `Vec<Mixin>` as there are additional validation rules: https://github.com/buildpacks/spec/blob/platform/v0.6/platform.md#mixins

**Comment by edmorley** [comment]
Yeah I thought it might have just been a rough sketch - just wanted to check I hadn't misunderstood the spec, or if we were choosing to interpret the spec a bit more sensibly.

I'll play around with the types locally and see what makes sense :-)
