### ISSUE TITLE
Naming consistency: `BuildpackToml` and `buildpack_descriptor`

### ISSUE THREAD

**Issue by Malax** [Malax/libcnb.rs#168]
We currently have a `BuildpackToml` type that was renamed from `BuildpackDescriptor` some time ago. We also have a `buildpack_descriptor` field in the `DetectContext` and `BuildContext` that returns that type.

We should have consistent naming for it. We should either rename the type back to `BuildpackDescriptor` or change the field name to `buildpack_toml`. 

@schneems made a comment about the fact that it wasnt obvious for him that `buildpack_descriptor` is the `buildpack.toml` file. (https://github.com/Malax/libcnb.rs/pull/144#discussion_r751516238)

**Comment by edmorley** [comment]
There are so many overloaded terms in the CNB spec, plus many things without an explicit name - it's quite frustrating.

For example we can't really rename `BuildpackToml` to `BuildpackMetadata`, since within the file there is also a `metadata` table. And similarly, we can't rename it instead to `Buildpack`, because there's a nested `buildpack` table too.

I see "Buildpack descriptor" is a term referenced in the docs:
https://github.com/buildpacks/spec/blob/main/buildpack.md#buildpacktoml-toml

...though I agree it's not immediately intuitive.

One option, would be to rename `BuildpackToml` to `Buildpack`, and have it accessible from the context via `buildpack`, and then to avoid the nested `buildpack` key with the same name, flatten those keys into the top-level during deserialisation, giving something like:

```
context.buildpack.api
context.buildpack.name
context.buildpack.stacks
```
