### ISSUE TITLE
Figure out how to support multiple buildpack API versions 

### ISSUE THREAD

**Issue by Malax** [Malax/libcnb.rs#29]

**Comment by Malax** [comment]
I'm currently leaning towards 1 since it's the most simple implementation both in terms of maintenance and usage. Unless we have a great use-case for 2 and 3 I'd hold off implementing them, especially pre `1.0` where our API will change often and drastically.

**Comment by edmorley** [comment]
I'm leaning towards (1) too.

The only reason I can see for needing to support multiple buildpack API versions in the same libcnb.rs release is if we regularly encounter situations where we need to release a bug fix or feature for users who are somehow stuck on an older buildpack API version.

And since a build can use buildpacks with a mixture of buildpack API versions, updating an individual buildpack's API version should be something that's generally easy, since it's not blocked on updating everything at once. Users will obviously need to be on a recent Pack CLI/`lifecycle` release, however it's not like `libcnb.rs` will support a new buildpack API version the instant it's released, so there's going to be lag on both sides anyway.

For one-off issues we can always release libcnb.rs hotfixes off a release branch.

**Comment by hone** [comment]
@edmorley I think buildpacks API are going to be generally compatible across groups, but I don't think lifecycle can actually make that guarantee always and it's always best effort.

I think step 1 might be to just get the current API up to snuff with `0.5` then support `0.6`.

**Comment by Malax** [comment]
I agree that we should at first document and ensure we support one specific API version properly.

**Comment by hone** [comment]
@malax this feels like a DR, we should capture it (maybe in this repo). Thoughts?

**Comment by Malax** [comment]
IDK if we need a DR document in this repo, but we need to document the strategy and currently supported version of the CNB spec in here :100:. Maybe in the `README` for now? I don't have a strong opinion other than that it needs to be documented.

**Comment by hone** [comment]
For some prior art, the paketo buildpacks used to have a RFCs folder in the
repo. Maybe it's worth doing something similar with a DR?
https://github.com/paketo-buildpacks/nodejs/tree/main/rfcs

**Comment by schneems** [comment]
> Maybe it's worth doing something similar with a DR

I'm +1 on that. I would like to close out this issue (productively) and it seems to document this and saying "here's the convo, here's what we decided" would be a good way forward).

**Comment by edmorley** [comment]
We've currently settled on supporting only one version of the buildpack API (which IMO is the best option).

The currently supported API version is documented in the README:
https://github.com/Malax/libcnb.rs/blame/main/README.md#L14

I think we should close this out for now - for future design decisions we can always create DRs, however right now that's a lot of work for little benefit given how much other higher-priority work needs addressing in libcnb.rs first.
