### ISSUE TITLE
Infinite loop with `cargo watch` and `libcnb-test`

### ISSUE THREAD

**Issue by schneems** [Malax/libcnb.rs#303]
It looks like libcnb-test modifies the current directory which triggers cargo test, which modifies the current directory, which...

https://user-images.githubusercontent.com/59744/152241630-38dd9d81-b354-4291-aa30-c2c0d7b53622.mp4

**Comment by edmorley** [comment]
What does --debug output as the changed file that caused the reload? 

By default, cargo watch ignores `target/` and anything in `.gitignore`, which should mean this shouldn't happen.

**Comment by edmorley** [comment]
Actually, `--why` (without the `--clear`) is easier to follow than `--debug`.

Trying locally on the currently pushed procfile rewrite branch shows:

```
2022-02-02T23:00:20.986+00:00 - INFO - Paths updated: [PathOp { path: "/Users/emorley/src/procfile-cnb-rust/tests/fixtures/app_with_procfile/Procfile", op: Some((empty)), cookie: None }, PathOp { path: "/Users/emorley/src/procfile-cnb-rust/buildpack.toml", op: Some((empty)), cookie: None }]
```

**Comment by edmorley** [comment]
This seems like a bug with either cargo-watch, watchman or inotify (the libraries it relies upon). I've filed:
https://github.com/watchexec/cargo-watch/issues/193

**Comment by edmorley** [comment]
This appears to be a quirk with FSEvents (the macOS file system event API) and cargo watch - so:
1. Is not a libcnb-specific issue
2. Only affects macOS
3. Appears to be fixed in the newer version of the watchexec library (which cargo watch will eventually upgrade to)

This can be worked around for now by using `watchexec` directly, rather than via `cargo-watch` - see installation/usage instructions here:
https://watchexec.github.io/
