### ISSUE TITLE
Expose `toml::value::Table` to consumers of the crate

### ISSUE THREAD

**Issue by edmorley** [Malax/libcnb.rs#71]
This is a review comment split out of https://github.com/Malax/libcnb.rs/pull/28#pullrequestreview-705465664.

If this suggestion ends up being wontfix we can always close this issue out, however I didn't want it to get lost given that the PR was already merged :-)

> * We should be exposing `toml::value::Table` if we expect users to use this as part of the crate.
> -- @hone

**Comment by Malax** [comment]
I'm not sure how much I agree here. `pub use`ing `toml::value::Table` would create `libcnb::Table` which effectively is just an alias and Rust's compiler is smart enough to realize `toml::value::Table` and `libcnb::Table` are the same type:

```rust
let x = libcnb::Value::Integer(23);
let y = toml::Value::Integer(23);

assert_eq!(x, y)
```

However, this would need to be documented somewhere when users want to use the "regular" toml types because it's not immediately obvious that we're just re-exporting. Even if we'd re-export `toml::Value`, users would need `toml::value::Table` as well to effectively work with it. Should we re-export this as well?

I'm worried that this is a slippery slope where, in the end, we re-export the whole `toml` crate and pollute our `libcnb` namespace with `toml` crate exports. In return, we get that users don't need to declare a dependency on `toml` if they want to use raw toml.

For me, this does not sound like a good trade-off.

**Comment by edmorley** [comment]
Yeah I agree

**Comment by hone** [comment]
> In return, we get that users don't need to declare a dependency on toml if they want to use raw toml.

I think there's more nuance than that there and it's a bit of a judgement call of what we want from the API. I've used crates that either wrap a type to make it their own, re-export, or forces you to pull it in, though that does require us to be somewhat careful on features we use in the `toml`crate if it's part of our public API. There's a pretty [good discussion on this exact issue](https://github.com/rust-lang/api-guidelines/discussions/176#discussioncomment-232636). In `reqwest`, it [re-exports parts of the `tls` crate](https://docs.rs/reqwest/0.11.6/reqwest/index.html#reexports).
